site_name: Projet Edimbourg
site_description: BTS SIO SISR - Mise en place d'une agence à Edimbourg
site_author: Louis Biseray
repo_url: https://github.com/louisbiseray-bot/Edimbourg

docs_dir: docs_edimbourg

theme:
  name: material
  language: fr
  palette:
    primary: indigo
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest

nav:
  - Accueil: readme.md
  - Documentation:
    - Réseaux - Systèmes:
        - Situation 1:
            - Réseaux - Systèmes\Situation 1\Déploiement d'une VM Windows Core.md
            - Réseaux - Systèmes\Situation 1\Préparation de la maquette.md
        - Situation 2:
            - Réseaux - Systèmes\Situation 2\WAC - Windows Admin Center.md
    - Cybersecuriter :
        - Cybersecuriter\Phase d'analyse Préalable.md
    - Services :
        - Services\Mise en place d'une machine Debian 13 servant de modèle.md
    - Table de Routage.md
    - Table NAT.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - codehilite

plugins:
  - search

  